# Generated by Django 4.2.7 on 2023-11-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0002_alter_contato_options_contato_estado_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='bairro',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contato',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascença'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='estado',
            field=models.CharField(choices=[('SP', 'São Paulo'), ('MG', 'Minas Gerais'), ('RJ', 'Rio de Janeiro'), ('ES', 'Espírito Santo')], max_length=2),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
